
spring:
  profiles:
    active: prod

---

spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db_username}
    password: ${db_password}
    url: jdbc:mysql://localhost:3306/trello
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

jwt:
  secret:
    key: ${jwt_secret_key}

cloud: # S3
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${s3_bucket_name}
    region:
      static: ap-northeast-2
    stack:
      auto: false

---

spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${aws_db_username}
    password: ${aws_db_password}
    url: jdbc:mysql://mydbinstance.civimbswi832.ap-northeast-2.rds.amazonaws.com:3306/trello
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

jwt:
  secret:
    key: ${jwt_secret_key}

cloud: # S3
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${s3_bucket_name}
    region:
      static: ap-northeast-2
    stack:
      auto: false